name: CI

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: ["0.14.0"]
        os: [ubuntu-latest, windows-latest]
        include:
          - zig-version: "0.14.0"
            check-format: true
            os: macos-latest
            build-options: "-Dbuild-tests -Dbuild-benchmarks"

          - zig-version: "master"
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - if: ${{ matrix.check-format }}
        name: Check Formatting
        run: zig fmt --check --ast-check .

      - name: Build
        run: zig build ${{ matrix.build-options }} --summary all
